services:
  wgbot:
    image: goomboldt/wgbot:latest
    container_name: wgbot
    restart: unless-stopped
    environment:
      # Telegram Bot Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      
      # YooKassa Configuration
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - YOOKASSA_PROVIDER_TOKEN=${YOOKASSA_PROVIDER_TOKEN}
      
      # WGDashboard Configuration
      - WG_DASHBOARD_URL=${WG_DASHBOARD_URL}
      - WG_DASHBOARD_API_KEY=${WG_DASHBOARD_API_KEY}
      
      # Database Configuration
      - DATABASE_PATH=/app/data/wgbot.db
      
      # Logging Configuration (минимальный уровень)
      - LOG_LEVEL=WARNING
      
    volumes:
      # Только база данных, логи в контейнере
      - wgbot-data:/app/data
      
    networks:
      - wgbot-network
      
    # Минимальный health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.getenv('TELEGRAM_BOT_TOKEN') else 1)"]
      interval: 120s
      timeout: 5s
      retries: 1
      start_period: 120s
    
    # Минимальные ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.9'
        reservations:
          memory: 50M
          cpus: '0.05'
    
    # Минимальная безопасность
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=25m

networks:
  wgbot-network:
    driver: bridge

volumes:
  wgbot-data:
    driver: local
